services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - urlServiceNetwork

  urlshorteningservice:
    image: urlshorteningservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortening-service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - server.port=8080
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.username=root
      - spring.data.mongodb.password=root
      - spring.data.mongodb.authentication-database=admin
      - spring.data.mongodb.database=url-shortener
    networks:
      - urlServiceNetwork

networks:
  urlServiceNetwork:

volumes:
  mongodb_data: